### ISSUE TITLE
Default sort on the heatmap table example

### ISSUE THREAD

**Issue by pbeshai** [pbeshai/react-taco-table#15]
This will help demonstrate the scale of the heatmap

**Comment by ccoat2** [comment]
How can we choose the order of coloration (exemple: darker for the max and lighter for the min or the reverse ) ?

**Comment by pbeshai** [comment]
Hmm. There's no direct option for doing this right now, although maybe it's worth adding if you want to use the domain based on the column summary information (e.g. the min and max as the default is). 

If you are providing the domain manually, you can just reverse the array.

For example, you could set `domain` to be `[9, 2]` in this example to reverse the coloring.

``` js
{
    id: 'level-1',
    type: DataType.NumberOrdinal,
    value: rowData => rowData.level,
    plugins: {
      heatmap: {
        // specify a domain to use instead of min, max in the data
        domain: [2, 9],

        // specfy an alternate background scale
        backgroundScale: d3.scaleLinear().range(['#404', '#fff']).clamp(true),
      },
    },
  },
```

You can alternatively set the `backgroundScale` manually which is also a pain. I think I'll add in a way to do it easily in the plugin.

**Comment by pbeshai** [comment]
Added new configuration option `reverseColors`. See example on site

http://pbeshai.github.io/react-taco-table/examples.html#example-heatmap

``` js
  // this column reverses the color scheme
  {
    id: 'value-reverse',
    type: DataType.Number,
    value: rowData => rowData.value,
    renderer: Formatters.plusMinusFormat(1),
    plugins: {
      heatmap: {
        reverseColors: true,
      },
    },
  }
```
