### ISSUE TITLE
Clickable row

### ISSUE THREAD

**Issue by ccoat2** [pbeshai/react-taco-table#19]
Can we click on a row and call a callback function like the handleMouseEnter() method?

**Comment by pbeshai** [comment]
Added `onRowClick` to TacoTable and `onClick` to TacoTableRow. The callback is passed `rowData` as a parameter. (0.1.5)

**Comment by ccoat2** [comment]
Thanks to be so reactive your component is great! !!!!!

**Comment by clementdevos** [comment]
Hey @pbeshai , do you think it would be possible to add the onRowDoubleCkcik callback? 

Cheers !

**Comment by pbeshai** [comment]
Added in 0.2.1
