### ISSUE TITLE
BottomData row doesn't have its own property

### ISSUE THREAD

**Issue by ccoat2** [pbeshai/react-taco-table#23]
I would like to disable the click and the heatmap plugin on the BottomData row I don't know how to do it

**Comment by pbeshai** [comment]
This is resolved in 0.2.0.

You can check for the `isBottomData` argument in your row click handler, which now has the following signature:

```
onRowClick(rowData, rowNumber, isBottomData)
```

The heatmap plugin by default will no longer color in the bottom row. Note there are some changes to the column definition function signatures now. They now take an object as arguments. The new signatures are documented here: https://github.com/pbeshai/react-taco-table/blob/master/CHANGES.md

**Comment by ccoat2** [comment]
thank you awesome
