### ISSUE TITLE
Ability to add custom data tags to rows

### ISSUE THREAD

**Issue by kieckhafer** [pbeshai/react-taco-table#43]
Is there the ability to add custom data tags, such as `data-event-action` or `data-event-data` to a row?

The end goal is to make an entire row clickable, with the data-attribute being used to process the click.

**Comment by pbeshai** [comment]
I'm not sure I understand exactly. You can pass an `onRowClick` handler to `<TacoTable>` -- is that not sufficient for your needs?

See: http://peterbeshai.com/react-taco-table/docs/TacoTable.html
